namespace FrontalierApp.Services;

public static class Strings
{
    private static readonly Dictionary<(string lang, string key), string> _t = new()
    {
        // App / Nav
        [("fr","app_name")]        = "Suivi télétravail",
        [("en","app_name")]        = "Telework Tracker",
        [("fr","nav_dashboard")]   = "Tableau de bord",
        [("en","nav_dashboard")]   = "Dashboard",
        [("fr","nav_calendar")]    = "Calendrier",
        [("en","nav_calendar")]    = "Calendar",
        [("fr","nav_log")]         = "Journal",
        [("en","nav_log")]         = "Log",
        [("fr","nav_export")]      = "Export",
        [("en","nav_export")]      = "Export",
        [("fr","nav_settings")]    = "Paramètres",
        [("en","nav_settings")]    = "Settings",

        // Calendar
        [("fr","today")]           = "Aujourd'hui",
        [("en","today")]           = "Today",
        [("fr","not_logged")]      = "Non enregistré",
        [("en","not_logged")]      = "Not logged",
        [("fr","legend")]          = "Légende",
        [("en","legend")]          = "Legend",

        // Settings
        [("fr","settings_ph")]        = "Jours fériés officiels — Genève",
        [("en","settings_ph")]        = "Official Public Holidays — Geneva",
        [("fr","settings_vac")]       = "Mes vacances",
        [("en","settings_vac")]       = "My Vacations",
        [("fr","settings_company")]   = "Entreprise, Régional & R&R",
        [("en","settings_company")]   = "Company, Regional & R&R",
        [("fr","in_calendar")]        = "Dans le calendrier",
        [("en","in_calendar")]        = "In calendar",
        [("fr","add_to_cal")]         = "Ajouter",
        [("en","add_to_cal")]         = "Add",
        [("fr","remove_from_cal")]    = "Retirer",
        [("en","remove_from_cal")]    = "Remove",
        [("fr","note_optional")]      = "Nom (optionnel)",
        [("en","note_optional")]      = "Name (optional)",
        [("fr","no_vacations")]       = "Aucune vacance enregistrée pour {0}",
        [("en","no_vacations")]       = "No vacations recorded for {0}",
        [("fr","no_company")]         = "Aucune entrée pour {0}",
        [("en","no_company")]         = "No entries for {0}",
        [("fr","x_days")]             = "{0} jour(s)",
        [("en","x_days")]             = "{0} day(s)",

        // Day types
        [("fr","type_ch")]   = "🇨🇭 Suisse (bureau)",
        [("en","type_ch")]   = "🇨🇭 Switzerland (office)",
        [("fr","type_tw")]   = "🏠 Télétravail (France)",
        [("en","type_tw")]   = "🏠 Telework (France)",
        [("fr","type_mis")]  = "✈️ Mission hors Suisse",
        [("en","type_mis")]  = "✈️ Mission abroad",
        [("fr","type_hol")]      = "🌴 Vacances",
        [("en","type_hol")]      = "🌴 Vacation",
        [("fr","type_ph")]       = "🏛️ Férié officiel",
        [("en","type_ph")]       = "🏛️ Public holiday",
        [("fr","type_company")]  = "🏢 Entreprise",
        [("en","type_company")]  = "🏢 Company holiday",
        [("fr","type_regional")] = "🗺️ Régional",
        [("en","type_regional")] = "🗺️ Regional holiday",
        [("fr","type_rnr")]      = "💆 R&R",
        [("en","type_rnr")]      = "💆 R&R",
        [("fr","type_sick")] = "🤒 Maladie",
        [("en","type_sick")] = "🤒 Sick leave",
        [("fr","lbl_ch")]    = "Suisse",
        [("en","lbl_ch")]    = "Switzerland",
        [("fr","lbl_tw")]    = "Télétravail",
        [("en","lbl_tw")]    = "Telework",
        [("fr","lbl_mis")]   = "Mission",
        [("en","lbl_mis")]   = "Mission",
        [("fr","lbl_hol")]      = "Vacances",
        [("en","lbl_hol")]      = "Vacation",
        [("fr","lbl_ph")]       = "Férié",
        [("en","lbl_ph")]       = "Holiday",
        [("fr","lbl_company")]  = "Entreprise",
        [("en","lbl_company")]  = "Company",
        [("fr","lbl_regional")] = "Régional",
        [("en","lbl_regional")] = "Regional",
        [("fr","lbl_rnr")]      = "R&R",
        [("en","lbl_rnr")]      = "R&R",
        [("fr","lbl_sick")]  = "Maladie",
        [("en","lbl_sick")]  = "Sick",

        // Dashboard alerts
        [("fr","alert_urssaf_title")]  = "Sécurité sociale française !",
        [("en","alert_urssaf_title")]  = "French social security!",
        [("fr","alert_urssaf_body")]   = "Vous avez dépassé 50% de télétravail. Votre employeur doit cotiser à l'URSSAF française.",
        [("en","alert_urssaf_body")]   = "You have exceeded 50% telework. Your employer must contribute to French URSSAF.",
        [("fr","alert_a1_title")]      = "Certificat A1 requis.",
        [("en","alert_a1_title")]      = "A1 Certificate required.",
        [("fr","alert_a1_body")]       = "Vous avez dépassé 25% de télétravail. Votre employeur doit demander un certificat A1 via le portail ALPS.",
        [("en","alert_a1_body")]       = "You have exceeded 25% telework. Your employer must apply for an A1 certificate via the ALPS portal.",
        [("fr","alert_cmu")]           = "CMU : Une attestation de droits (Ameli) récente sera nécessaire.",
        [("en","alert_cmu")]           = "CMU: A recent rights certificate (Ameli) will be required.",
        [("fr","alert_ss_approach")]   = "Approche du seuil SS. Vous approchez 25% — vérifiez si votre employeur dispose d'un certificat A1.",
        [("en","alert_ss_approach")]   = "Approaching Sécurité Sociale threshold. You are nearing 25% — check if your employer has an A1 certificate.",
        [("fr","alert_tax_exceed")]    = "Seuil fiscal dépassé ! Vous avez dépassé 40% — vos revenus sont imposables en France dès le premier jour.",
        [("en","alert_tax_exceed")]    = "Tax threshold exceeded! You have exceeded 40% — your income is taxable in France from day one.",
        [("fr","alert_tax_approach")]  = "Proche du seuil fiscal (40%). Limitez le télétravail pour rester imposé en Suisse.",
        [("en","alert_tax_approach")]  = "Close to tax threshold (40%). Limit telework to remain taxed in Switzerland.",
        [("fr","alert_mis_at")]        = "Plafond de 10 jours de missions atteint ! Toute mission supplémentaire aggrave votre situation fiscale.",
        [("en","alert_mis_at")]        = "10-day mission limit reached! Any additional mission worsens your tax situation.",
        [("fr","alert_mis_near")]      = "{0}/10 jours de missions. Vous approchez la limite annuelle de 10 jours.",
        [("en","alert_mis_near")]      = "{0}/10 mission days. You are approaching the annual 10-day limit.",

        // Dashboard cards
        [("fr","card_ss_title")]   = "Sécurité sociale",
        [("en","card_ss_title")]   = "Social Security",
        [("fr","card_ss_sub")]     = "{0} days telework / {1} days worked",  // overridden below
        [("en","card_ss_sub")]     = "{0} days telework / {1} days worked",
        [("fr","card_tax_title")]  = "Fiscal (imposition)",
        [("en","card_tax_title")]  = "Tax (income)",
        [("fr","card_tax_sub")]    = "{0} j (télétravail + missions) / {1} j travaillés",
        [("en","card_tax_sub")]    = "{0} days (telework + missions) / {1} days worked",
        [("fr","card_mis_title")]  = "Missions hors Suisse",
        [("en","card_mis_title")]  = "Missions outside Switzerland",
        [("fr","card_mis_note")]   = "Ces jours comptent également dans le quota fiscal de 40%.",
        [("en","card_mis_note")]   = "These days also count toward the 40% tax quota.",
        [("fr","summary_title")]   = "Récapitulatif {0}",
        [("en","summary_title")]   = "Summary {0}",
        [("fr","cmu_check")]       = "Assurance maladie",
        [("en","cmu_check")]       = "Health insurance",
        [("fr","label_year")]      = "Année :",
        [("en","label_year")]      = "Year:",

        // Badges
        [("fr","badge_urssaf")]     = "Sécu française",
        [("en","badge_urssaf")]     = "French social sec.",
        [("fr","badge_a1")]         = "Certificat A1 requis",
        [("en","badge_a1")]         = "A1 Certificate required",
        [("fr","badge_approach25")] = "Approche 25%",
        [("en","badge_approach25")] = "Approaching 25%",
        [("fr","badge_ss_ok")]      = "Système suisse OK",
        [("en","badge_ss_ok")]      = "Swiss system OK",
        [("fr","badge_fr_tax")]     = "Imposé en France",
        [("en","badge_fr_tax")]     = "Taxed in France",
        [("fr","badge_approach40")] = "Proche 40%",
        [("en","badge_approach40")] = "Approaching 40%",
        [("fr","badge_ch_tax")]     = "Imposé en Suisse OK",
        [("en","badge_ch_tax")]     = "Taxed in Switzerland OK",

        // Journal / Log
        [("fr","page_log")]      = "Journal des jours",
        [("en","page_log")]      = "Work Log",
        [("fr","import_title")]  = "Import",
        [("en","import_title")]  = "Import",
        [("fr","import_label")]  = "Fichier Envoy (attendance-calendar.csv)",
        [("en","import_label")]  = "Envoy file (attendance-calendar.csv)",
        [("fr","import_hint")]   = "Doublons ignorés",
        [("en","import_hint")]   = "Duplicates skipped",
        [("fr","range_title")]   = "Modifier une plage",
        [("en","range_title")]   = "Edit date range",
        [("fr","range_from")]    = "Du",
        [("en","range_from")]    = "From",
        [("fr","range_to")]      = "Au",
        [("en","range_to")]      = "To",
        [("fr","range_apply")]   = "Appliquer",
        [("en","range_apply")]   = "Apply",
        [("fr","add_title")]     = "Ajouter un jour",
        [("en","add_title")]     = "Add a day",
        [("fr","edit_title")]    = "Modifier",
        [("en","edit_title")]    = "Edit",
        [("fr","label_date")]    = "Date",
        [("en","label_date")]    = "Date",
        [("fr","label_half")]    = "Demi-journée",
        [("en","label_half")]    = "Half day",
        [("fr","btn_add")]       = "Ajouter",
        [("en","btn_add")]       = "Add",
        [("fr","btn_save")]      = "Enregistrer",
        [("en","btn_save")]      = "Save",
        [("fr","btn_cancel")]    = "Annuler",
        [("en","btn_cancel")]    = "Cancel",
        [("fr","no_entries")]    = "Aucune entrée pour {0}",
        [("en","no_entries")]    = "No entries for {0}",
        [("fr","entries")]       = "entrée(s)",
        [("en","entries")]       = "entries",

        // Export
        [("fr","page_export")]    = "Export",
        [("en","page_export")]    = "Export",
        [("fr","stats_title")]    = "Statistiques {0}",
        [("en","stats_title")]    = "Statistics {0}",
        [("fr","export_total")]   = "Jours travaillés total",
        [("en","export_total")]   = "Total worked days",
        [("fr","export_tw_ss")]   = "Télétravail — Sécu sociale (demi-j = 0.5)",
        [("en","export_tw_ss")]   = "Telework — Social Security (half-day = 0.5)",
        [("fr","export_ss_pct")]  = "% Sécurité sociale",
        [("en","export_ss_pct")]  = "% Social Security",
        [("fr","export_tw_tax")]  = "Télétravail — Fiscal (demi-j = 1 jour)",
        [("en","export_tw_tax")]  = "Telework — Tax (half-day = 1 day)",
        [("fr","export_mis")]     = "Missions hors Suisse",
        [("en","export_mis")]     = "Missions outside Switzerland",
        [("fr","export_tax_pct")] = "% Fiscal (télétravail + missions)",
        [("en","export_tax_pct")] = "% Tax (telework + missions)",
        [("fr","btn_csv")]        = "⬇ Télécharger CSV",
        [("en","btn_csv")]        = "⬇ Download CSV",
        [("fr","detail_title")]   = "Détail des entrées",
        [("en","detail_title")]   = "Entry details",
        [("fr","col_half_yes")]   = "Oui",
        [("en","col_half_yes")]   = "Yes",
        [("fr","col_date")]       = "Date",
        [("en","col_date")]       = "Date",
        [("fr","col_type")]       = "Type",
        [("en","col_type")]       = "Type",
        [("fr","col_half")]       = "Demi-journée",
        [("en","col_half")]       = "Half day",
    };

    // Fix card_ss_sub for French
    static Strings()
    {
        _t[("fr", "card_ss_sub")] = "{0} j télétravail / {1} j travaillés";
    }

    public static string Get(string lang, string key) =>
        _t.TryGetValue((lang, key), out var val) ? val :
        _t.TryGetValue(("en", key), out var fb)  ? fb  : key;
}
