<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.15" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="FrontalierApp.Shared\FrontalierApp.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FrontalierApp.Shared\**" />
    <Content Remove="FrontalierApp.Shared\**" />
    <EmbeddedResource Remove="FrontalierApp.Shared\**" />
    <None Remove="FrontalierApp.Shared\**" />
    <Compile Remove="FrontalierApp.Maui\**" />
    <Content Remove="FrontalierApp.Maui\**" />
    <EmbeddedResource Remove="FrontalierApp.Maui\**" />
    <None Remove="FrontalierApp.Maui\**" />
  </ItemGroup>

</Project>
